# Generated by Django 5.0.6 on 2024-06-03 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesero',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='observaciones',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.orden'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='orden',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.mesero')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.restaurante')),
            ],
        ),
    ]
