# Generated by Django 5.0.6 on 2024-06-03 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0002_remove_mesero_charge_remove_orden_observaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cost_per_unit', models.IntegerField()),
                ('all_restaurants', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('person_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='restaurante',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='mesero',
            name='restaurante',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='mesero',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='restaurante',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='restaurante',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='restaurante',
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tip_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsRestaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.product')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='TablesRestaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.table')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='table_restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.tablesrestaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.user'),
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('charge', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.user')),
            ],
        ),
        migrations.CreateModel(
            name='TipWaiter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paid', models.BooleanField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.bill')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.waiter')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.waiter'),
        ),
        migrations.CreateModel(
            name='WaiterShift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.restaurant')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.waiter')),
            ],
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.DeleteModel(
            name='Mesa',
        ),
        migrations.DeleteModel(
            name='Mesero',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Restaurante',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
