# Generated by Django 5.0.6 on 2024-06-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0003_order_product_restaurant_table_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiter',
            name='charge',
            field=models.CharField(choices=[('MG', 'MANAGER'), ('AT', 'ADMINTABLES'), ('EX', 'EXTRA')], max_length=50),
        ),
    ]
